apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: bitnami/wordpress:6.5.3-debian-12-r6
        env:
          - name: WORDPRESS_USERNAME
            value: "user"
          - name: WORDPRESS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: WORDPRESS_PASSWORD
          - name: WORDPRESS_EMAIL
            value: "user@example.com"
          - name: WORDPRESS_FIRST_NAME
            value: "FirstName"
          - name: WORDPRESS_LAST_NAME
            value: "LastName"
          - name: WORDPRESS_BLOG_NAME
            value: "User's Blog"
          - name: WORDPRESS_DATABASE_HOST
            value: "mariadb"
          - name: WORDPRESS_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: MARIADB_DATABASE
          - name: WORDPRESS_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: MARIADB_USER
          - name: WORDPRESS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: MARIADB_PASSWORD
          - name: MEMCACHED_HOST
            value: "memcached"
          - name: MEMCACHED_PORT
            value: "11211"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /bitnami/wordpress
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc

